
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import PageTransition from "../components/PageTransition";
import StairsTransition from "../components/StairsTransition"
import { SpeedInsights } from '@vercel/speed-insights/next';


const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800"],
  variable: "--font-jetbrainsMono",
});

export const metadata = {
  title: "Developing Dreams | Asad Abbas",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={jetbrainsMono.variable}
      >
        <Header/>
        <StairsTransition/>
        <PageTransition>
        {children}
        <SpeedInsights/>
        </PageTransition>
      </body>
    </html>
  );
}
